flowchart LR
  x1[Input t-3] --> H1[Hidden t-3]
  x2[Input t-2] --> H2[Hidden t-2]
  x3[Input t-1] --> H3[Hidden t-1]
  x4[Input t] --> H4[Hidden t]
  H1 --> H2 --> H3 --> H4
  classDef f stroke:#2C5F77,stroke-width:2px