name: Publish Quarto Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch last 2 commits to detect changes

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: release

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Cache Python virtual environment
        uses: actions/cache@v4
        id: venv-cache
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install Python dependencies
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Activate virtual environment
        if: steps.venv-cache.outputs.cache-hit == 'true'
        run: echo "Using cached virtual environment"

      - name: Cache Quarto freeze
        uses: actions/cache@v4
        with:
          path: _freeze
          key: ${{ runner.os }}-quarto-freeze-${{ hashFiles('**/*.qmd', '**/*.ipynb') }}
          restore-keys: |
            ${{ runner.os }}-quarto-freeze-

      - name: Set site URL for fork-friendly deployment
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          GITHUB_USER="${GITHUB_REPOSITORY%/*}"
          SITE_URL="https://${GITHUB_USER}.github.io/${REPO_NAME}"
          echo "  site-url: ${SITE_URL}" >> _quarto.yml
          sed -i "s|icon: github|icon: github\n        href: https://github.com/${GITHUB_REPOSITORY}|" _quarto.yml
          echo "Deploying to: ${SITE_URL}"

      - name: Render Quarto site
        run: |
          # Activate virtual environment and render
          source venv/bin/activate
          # Freeze feature prevents re-executing unchanged notebooks
          # This dramatically speeds up rendering
          quarto render

      - name: Copy pre-generated PDFs to site
        run: |
          cp -r pdfs/day1/*.pdf _site/day1/presentations/
          cp -r pdfs/day2/*.pdf _site/day2/presentations/
          cp -r pdfs/day3/*.pdf _site/day3/presentations/
          cp -r pdfs/day4/*.pdf _site/day4/presentations/
          echo "PDFs copied to _site directories"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
